name: python setup

on:
  workflow_dispatch:

jobs:
  python-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # You can change this to any version you need
      - name: Print Python Version
        run: python --version
